/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.controller.EstoqueCntrl;
import br.com.controller.Tabela;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristiano
 */
public class EstoqueView extends javax.swing.JPanel {

    /**
     * Creates new form EstoqueView
     */
    public EstoqueView() {
        initComponents();
        this.preencheTabela(null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLBTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBEstoque = new javax.swing.JTable();
        jBTListar = new javax.swing.JButton();
        jBTRetorno = new javax.swing.JButton();
        jBTAdicionar = new javax.swing.JButton();
        jPPesquisa = new javax.swing.JPanel();
        jLBPesquisa = new javax.swing.JLabel();
        jLBCategoria = new javax.swing.JLabel();
        jLBCapacidade = new javax.swing.JLabel();
        jFTFCapacidade = new javax.swing.JFormattedTextField();
        jBTBuscar = new javax.swing.JButton();
        jTFCategoria = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLBTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLBTitulo.setText("ESTOQUE");

        jTBEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTBEstoque);

        jBTListar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Renew_105218.png"))); // NOI18N
        jBTListar.setText("LISTAR");
        jBTListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTListarActionPerformed(evt);
            }
        });

        jBTRetorno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTRetorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Information_105260.png"))); // NOI18N
        jBTRetorno.setText("RETORNO");
        jBTRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTRetornoActionPerformed(evt);
            }
        });

        jBTAdicionar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Create_105261.png"))); // NOI18N
        jBTAdicionar.setText("ADICIONAR");
        jBTAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLBTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jBTAdicionar)
                .addGap(18, 18, 18)
                .addComponent(jBTRetorno)
                .addGap(18, 18, 18)
                .addComponent(jBTListar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLBTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTAdicionar)
                    .addComponent(jBTRetorno)
                    .addComponent(jBTListar))
                .addGap(16, 16, 16))
        );

        jPPesquisa.setBackground(new java.awt.Color(255, 255, 255));

        jLBPesquisa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLBPesquisa.setText("PESQUISA:");

        jLBCategoria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBCategoria.setText("CATEGORIA:");

        jLBCapacidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBCapacidade.setText("CAPACIDADE:");

        try {
            jFTFCapacidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCapacidade.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        jBTBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_search_magnifying_glass_find_103857.png"))); // NOI18N
        jBTBuscar.setText("BUSCAR");
        jBTBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPPesquisaLayout = new javax.swing.GroupLayout(jPPesquisa);
        jPPesquisa.setLayout(jPPesquisaLayout);
        jPPesquisaLayout.setHorizontalGroup(
            jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPPesquisaLayout.createSequentialGroup()
                        .addComponent(jLBCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCategoria))
                    .addGroup(jPPesquisaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPPesquisaLayout.createSequentialGroup()
                                .addComponent(jBTBuscar)
                                .addGap(6, 6, 6))
                            .addGroup(jPPesquisaLayout.createSequentialGroup()
                                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLBPesquisa)
                                    .addGroup(jPPesquisaLayout.createSequentialGroup()
                                        .addComponent(jLBCapacidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFTFCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)))))
                .addContainerGap())
        );
        jPPesquisaLayout.setVerticalGroup(
            jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLBPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBCategoria)
                    .addComponent(jTFCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBCapacidade)
                    .addComponent(jFTFCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBTBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBTAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAdicionarActionPerformed
        AdicionarRetornoDialogView dialog = new AdicionarRetornoDialogView(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jBTAdicionarActionPerformed

    private void jBTRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTRetornoActionPerformed
        ListaRetornoDialogView dialog = new ListaRetornoDialogView(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jBTRetornoActionPerformed

    private void jBTBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTBuscarActionPerformed
        String categoria = this.jTFCategoria.getText().trim();
        String cap = this.jFTFCapacidade.getText().trim();
        Integer capacidade = null;

        if (cap != null && !cap.isEmpty()) {
            try {
                capacidade = Integer.parseInt(cap);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        this.preencheTabela(capacidade, categoria);


    }//GEN-LAST:event_jBTBuscarActionPerformed

    private void jBTListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTListarActionPerformed
        this.preencheTabela(null, null);
    }//GEN-LAST:event_jBTListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTAdicionar;
    private javax.swing.JButton jBTBuscar;
    private javax.swing.JButton jBTListar;
    private javax.swing.JButton jBTRetorno;
    private javax.swing.JFormattedTextField jFTFCapacidade;
    private javax.swing.JLabel jLBCapacidade;
    private javax.swing.JLabel jLBCategoria;
    private javax.swing.JLabel jLBPesquisa;
    private javax.swing.JLabel jLBTitulo;
    private javax.swing.JPanel jPPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBEstoque;
    private javax.swing.JTextField jTFCategoria;
    // End of variables declaration//GEN-END:variables

    private void preencheTabela(Integer capacidade, String categoria) {
        String[] coluna = {"CÓDIGO", "PRODUTO", "QUANTIDADE"};
        EstoqueCntrl estCntrl = new EstoqueCntrl();
        List linha = estCntrl.listarTab(capacidade, categoria);
        Tabela tab = new Tabela(linha, coluna);
        this.jTBEstoque.setModel(tab);
    }

}
