/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.controller.EstoqueCntrl;
import br.com.controller.Tabela;
import java.util.List;

/**
 *
 * @author Cristiano
 */
public class ListaProdutosDialogView extends javax.swing.JDialog {

    /**
     * Creates new form ListaProdutosDialogView
     */
    public ListaProdutosDialogView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.preencheTabela(null, null);
        this.jBTAdicionar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLBTitulo = new javax.swing.JLabel();
        jBTAdicionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTBProdutos = new javax.swing.JTable();
        jBTListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLBTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLBTitulo.setText("QUANTIDADE DE PRODUTOS DISPONÍVEIS EM ESTOQUE");

        jBTAdicionar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Create_105261.png"))); // NOI18N
        jBTAdicionar.setText("ADICIONAR");
        jBTAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAdicionarActionPerformed(evt);
            }
        });

        jTBProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTBProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTBProdutos);

        jBTListar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Renew_105218.png"))); // NOI18N
        jBTListar.setText("LISTAR");
        jBTListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLBTitulo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jBTAdicionar)
                                .addGap(18, 18, 18)
                                .addComponent(jBTListar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLBTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTAdicionar)
                    .addComponent(jBTListar))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBTAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAdicionarActionPerformed
        String[] dados = this.pegaDados();
        this.setAdicionarVenda(dados);
    }//GEN-LAST:event_jBTAdicionarActionPerformed

    private void jTBProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBProdutosMouseClicked
        if (evt.getClickCount() == 1) {
            this.jBTAdicionar.setEnabled(true);
        }
        if (evt.getClickCount() == 2) {
            String[] dados = this.pegaDados();
            this.setAdicionarVenda(dados);
        }
    }//GEN-LAST:event_jTBProdutosMouseClicked

    private void jBTListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTListarActionPerformed
        this.preencheTabela(null, null);
        this.jBTAdicionar.setEnabled(false);
    }//GEN-LAST:event_jBTListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaProdutosDialogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaProdutosDialogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaProdutosDialogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaProdutosDialogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListaProdutosDialogView dialog = new ListaProdutosDialogView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTAdicionar;
    private javax.swing.JButton jBTListar;
    private javax.swing.JLabel jLBTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTBProdutos;
    // End of variables declaration//GEN-END:variables

    private void preencheTabela(Integer capacidade, String categoria) {
        String[] coluna = {"CÓDIGO", "PRODUTO", "QUANTIDADE"};
        EstoqueCntrl estCntrl = new EstoqueCntrl();
        List linha = estCntrl.listarTab(capacidade, categoria);
        Tabela tab = new Tabela(linha, coluna);
        this.jTBProdutos.setModel(tab);
    }

    private String[] pegaDados() {
        int linha = this.jTBProdutos.getSelectedRow();
        String[] lista = {this.jTBProdutos.getValueAt(linha, 0).toString(), this.jTBProdutos.getValueAt(linha, 1).toString()};
        return lista;
    }

    private void setAdicionarVenda(String[] dados) {
        int linha = this.jTBProdutos.getSelectedRow();
        AdicionarVendaDialogView dialog = new AdicionarVendaDialogView(new javax.swing.JFrame(), true);
        dialog.setCodigo(dados[0]);
        dialog.setProduto(dados[1]);
        dialog.setVisible(true);
    }

}
