/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.controller.MaquinaCntrl;
import br.com.controller.Tabela;
import br.com.exception.GenericSqlException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristiano
 */
public class MaquinaView extends javax.swing.JPanel {
    
    private final MaquinaCntrl MAQCNTRL = new MaquinaCntrl();

    /**
     * Creates new form MaquinaView
     */
    public MaquinaView() {
        initComponents();
        preencheTab();
        this.botoes(true, false, false, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBMaquina = new javax.swing.JTable();
        jBTAdicionar = new javax.swing.JButton();
        jBTAlterar = new javax.swing.JButton();
        jBTExcluir = new javax.swing.JButton();
        jBTListar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("MÁQUINA");

        jTBMaquina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTBMaquina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBMaquinaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTBMaquina);

        jBTAdicionar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Create_105261.png"))); // NOI18N
        jBTAdicionar.setText("ADICIONAR");
        jBTAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAdicionarActionPerformed(evt);
            }
        });

        jBTAlterar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Refresh_105225.png"))); // NOI18N
        jBTAlterar.setText("ALTERAR");
        jBTAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAlterarActionPerformed(evt);
            }
        });

        jBTExcluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Close_105221.png"))); // NOI18N
        jBTExcluir.setText("EXCLUIR");
        jBTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTExcluirActionPerformed(evt);
            }
        });

        jBTListar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Renew_105218.png"))); // NOI18N
        jBTListar.setText("LISTAR");
        jBTListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(223, 223, 223))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jBTAdicionar)
                .addGap(18, 18, 18)
                .addComponent(jBTAlterar)
                .addGap(18, 18, 18)
                .addComponent(jBTExcluir)
                .addGap(18, 18, 18)
                .addComponent(jBTListar)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTAdicionar)
                    .addComponent(jBTAlterar)
                    .addComponent(jBTExcluir)
                    .addComponent(jBTListar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBTAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAdicionarActionPerformed
        String maquina = JOptionPane.showInputDialog(null, "Máquina:");
        if (maquina != null && !maquina.isEmpty()) {
            try {
                if (MAQCNTRL.salvar(maquina.trim())) {
                    JOptionPane.showMessageDialog(null, "Adicionado com sucesso!");
                }
            } catch (GenericSqlException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jBTAdicionarActionPerformed

    private void jBTAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAlterarActionPerformed
        this.alterarMaquina();

    }//GEN-LAST:event_jBTAlterarActionPerformed

    private void jTBMaquinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBMaquinaMouseClicked
        if (evt.getClickCount() == 1) {
            this.botoes(true, true, true, true);
        }
        if (evt.getClickCount() == 2) {
            this.alterarMaquina();
        }
    }//GEN-LAST:event_jTBMaquinaMouseClicked

    private void jBTListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTListarActionPerformed
        this.preencheTab();
        this.botoes(true, false, false, true);
    }//GEN-LAST:event_jBTListarActionPerformed

    private void jBTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTExcluirActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esta máquina?");
        if (opcao == 0) {
            Integer linha = this.jTBMaquina.getSelectedRow();
            try {
                Integer codMaq = Integer.parseInt(this.jTBMaquina.getValueAt(linha, 0).toString());
                if (MAQCNTRL.apagar(codMaq)) {
                    JOptionPane.showMessageDialog(null, "Excluído com sucesso!");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Formato de número inválido!\n" + ex.getMessage());
            } catch (GenericSqlException ex1) {
                JOptionPane.showMessageDialog(null, ex1.getMessage());
            }
        }
    }//GEN-LAST:event_jBTExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTAdicionar;
    private javax.swing.JButton jBTAlterar;
    private javax.swing.JButton jBTExcluir;
    private javax.swing.JButton jBTListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBMaquina;
    // End of variables declaration//GEN-END:variables

    private void preencheTab() {
        List lista = MAQCNTRL.listarTabela();
        String[] linha = {"CÓDIGO", "MÁQUINA"};
        Tabela tab = new Tabela(lista, linha);
        this.jTBMaquina.setModel(tab);
    }
    
    private void botoes(boolean adicionar, boolean alterar, boolean excluir, boolean lista) {
        this.jBTAdicionar.setEnabled(adicionar);
        this.jBTAlterar.setEnabled(alterar);
        this.jBTExcluir.setEnabled(excluir);
        this.jBTListar.setEnabled(lista);
    }
    
    private void alterarMaquina() {
        Integer linha = this.jTBMaquina.getSelectedRow();
        String novaMaq = JOptionPane.showInputDialog(null, "Nova Máquina:");
        if (novaMaq != null && !novaMaq.isEmpty()) {
            
            try {
                Integer codMaq = Integer.parseInt(this.jTBMaquina.getValueAt(linha, 0).toString());
                if (MAQCNTRL.alterar(codMaq, novaMaq.trim())) {
                    JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");
                }
            } catch (GenericSqlException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (NumberFormatException ex1) {
                JOptionPane.showMessageDialog(null, "Formato de número inválido!\n" + ex1.getMessage());
            }
        }
    }
}
