/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.controller.CapacidadeCntrl;
import br.com.controller.CategoriaCntrl;
import br.com.controller.CorCntrl;
import br.com.controller.MaquinaCntrl;
import br.com.controller.ProducaoCntrl;
import br.com.controller.Tabela;
import br.com.controller.ValidacaoCntrl;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristiano
 */
public class ProducaoView extends javax.swing.JPanel {

    private final ProducaoCntrl PRODUCCNTRL = new ProducaoCntrl();
    private final String[] PRODUCAOTOTAL = {"PRODUTO", "QUANTIDADE"};

    /**
     * Creates new form ProducaoView
     */
    public ProducaoView() {
        initComponents();
        this.preencheTabDetalhes(null, null, null, null, null, null);
        this.preencheComboBoxCap();
        this.preencheComboBoxCat();
        this.preencheComboBoxCor();
        this.preencheComboBoxMaq();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBProducao = new javax.swing.JTable();
        jBTMes = new javax.swing.JButton();
        jBTSemana = new javax.swing.JButton();
        jBTAtual = new javax.swing.JButton();
        jBTListar = new javax.swing.JButton();
        jLBTitulo = new javax.swing.JLabel();
        jPPesquisa = new javax.swing.JPanel();
        jLBPesquisa = new javax.swing.JLabel();
        jLBCategoria = new javax.swing.JLabel();
        jLBCapacidade = new javax.swing.JLabel();
        jBTBuscarDet = new javax.swing.JButton();
        jLBCor = new javax.swing.JLabel();
        jCBCategoria = new javax.swing.JComboBox<>();
        jCBCapacidade = new javax.swing.JComboBox<>();
        jCBCor = new javax.swing.JComboBox<>();
        jLBData = new javax.swing.JLabel();
        jFTFData = new javax.swing.JFormattedTextField();
        jLBHora = new javax.swing.JLabel();
        jFTFHora = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLBMaquina = new javax.swing.JLabel();
        jCBMaquina = new javax.swing.JComboBox<>();
        jFTFData2 = new javax.swing.JFormattedTextField();
        jLBData2 = new javax.swing.JLabel();
        jBTBuscarMaq = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLBData3 = new javax.swing.JLabel();
        jFTFData3 = new javax.swing.JFormattedTextField();
        jBTBuscarTot = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTBProducao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTBProducao);

        jBTMes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_17_2169573.png"))); // NOI18N
        jBTMes.setText("MÊS");
        jBTMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTMesActionPerformed(evt);
            }
        });

        jBTSemana.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTSemana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_17_2169573.png"))); // NOI18N
        jBTSemana.setText("SEMANA");
        jBTSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSemanaActionPerformed(evt);
            }
        });

        jBTAtual.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTAtual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_17_2169573.png"))); // NOI18N
        jBTAtual.setText("ATUAL");
        jBTAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAtualActionPerformed(evt);
            }
        });

        jBTListar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Renew_105218.png"))); // NOI18N
        jBTListar.setText("LISTAR");
        jBTListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTListarActionPerformed(evt);
            }
        });

        jLBTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLBTitulo.setText("PRODUÇÃO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBTListar)
                .addGap(18, 18, 18)
                .addComponent(jBTAtual)
                .addGap(18, 18, 18)
                .addComponent(jBTSemana)
                .addGap(18, 18, 18)
                .addComponent(jBTMes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLBTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLBTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTListar)
                    .addComponent(jBTAtual)
                    .addComponent(jBTSemana)
                    .addComponent(jBTMes))
                .addGap(28, 28, 28))
        );

        jPPesquisa.setBackground(new java.awt.Color(255, 255, 255));

        jLBPesquisa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLBPesquisa.setText("PESQUISA DETALHADA");
        jLBPesquisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLBCategoria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBCategoria.setText("CATEGORIA:");

        jLBCapacidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBCapacidade.setText("CAPACIDADE:");

        jBTBuscarDet.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTBuscarDet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_search_magnifying_glass_find_103857.png"))); // NOI18N
        jBTBuscarDet.setText("BUSCAR");
        jBTBuscarDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTBuscarDetActionPerformed(evt);
            }
        });

        jLBCor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBCor.setText("COR:");

        jCBCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBCategoriaActionPerformed(evt);
            }
        });

        jCBCapacidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBCapacidade.setEnabled(false);
        jCBCapacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBCapacidadeActionPerformed(evt);
            }
        });

        jCBCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBCor.setEnabled(false);

        jLBData.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBData.setText("DATA:");

        try {
            jFTFData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFData.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        jLBHora.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBHora.setText("HORA:");

        try {
            jFTFHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFHora.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        javax.swing.GroupLayout jPPesquisaLayout = new javax.swing.GroupLayout(jPPesquisa);
        jPPesquisa.setLayout(jPPesquisaLayout);
        jPPesquisaLayout.setHorizontalGroup(
            jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPesquisaLayout.createSequentialGroup()
                        .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPPesquisaLayout.createSequentialGroup()
                                .addComponent(jLBCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPesquisaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBTBuscarDet))
                            .addGroup(jPPesquisaLayout.createSequentialGroup()
                                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPPesquisaLayout.createSequentialGroup()
                                        .addComponent(jLBCor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCBCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLBData))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPPesquisaLayout.createSequentialGroup()
                        .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jFTFData, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPPesquisaLayout.createSequentialGroup()
                                    .addComponent(jLBCapacidade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCBCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPPesquisaLayout.createSequentialGroup()
                                .addComponent(jLBHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLBPesquisa))
                        .addGap(0, 46, Short.MAX_VALUE))))
        );
        jPPesquisaLayout.setVerticalGroup(
            jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPesquisaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLBPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBCategoria)
                    .addComponent(jCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBCapacidade)
                    .addComponent(jCBCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBCor)
                    .addComponent(jCBCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBData)
                    .addComponent(jFTFData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBHora)
                    .addComponent(jFTFHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBTBuscarDet)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLBMaquina.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBMaquina.setText("MÁQUINA:");

        jCBMaquina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        try {
            jFTFData2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFData2.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        jLBData2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBData2.setText("DATA:");

        jBTBuscarMaq.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTBuscarMaq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_search_magnifying_glass_find_103857.png"))); // NOI18N
        jBTBuscarMaq.setText("BUSCAR");
        jBTBuscarMaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTBuscarMaqActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("PRODUÇÃO MAQUINA");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLBMaquina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBMaquina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBTBuscarMaq))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLBData2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFData2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBMaquina)
                    .addComponent(jCBMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBData2)
                    .addComponent(jFTFData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTBuscarMaq)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLBData3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBData3.setText("DATA:");

        try {
            jFTFData3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFData3.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        jBTBuscarTot.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTBuscarTot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_search_magnifying_glass_find_103857.png"))); // NOI18N
        jBTBuscarTot.setText("BUSCAR");
        jBTBuscarTot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTBuscarTotActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("PRODUÇÃO TOTAL");
        jLabel7.setToolTipText("");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBTBuscarTot))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLBData3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFData3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLBData3)
                    .addComponent(jFTFData3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBTBuscarTot)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBTBuscarTotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTBuscarTotActionPerformed
        if (!this.jFTFData3.getText().equals("  -  -    ")) {
            this.preencheTabTotalDia(ValidacaoCntrl.formataData(this.jFTFData3.getText()));
        } else {
            this.preencheTabTotalDia(null);
        }
    }//GEN-LAST:event_jBTBuscarTotActionPerformed

    private void jBTSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSemanaActionPerformed
        this.preencheTabTotalSemana();
    }//GEN-LAST:event_jBTSemanaActionPerformed

    private void jBTMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTMesActionPerformed
        this.preencheTabTotalMes();
    }//GEN-LAST:event_jBTMesActionPerformed

    private void jBTAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAtualActionPerformed
        this.preencheTabTotalDia(null);
    }//GEN-LAST:event_jBTAtualActionPerformed

    private void jBTBuscarMaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTBuscarMaqActionPerformed
        if (this.jCBMaquina.getSelectedIndex() != 0) {
            if (!this.jFTFData2.getText().equals("  -  -    ")) {
                this.preencheTabDetalhes(null, null, null, this.jCBMaquina.getSelectedItem().toString(), ValidacaoCntrl.formataData(this.jFTFData2.getText()), null);
            } else {
                this.preencheTabDetalhes(null, null, null, this.jCBMaquina.getSelectedItem().toString(), null, null);
            }
        } else {
            if (!this.jFTFData2.getText().equals("  -  -    ")) {
                this.preencheTabTotalMaq(ValidacaoCntrl.formataData(this.jFTFData2.getText()));
            } else {
                this.preencheTabTotalMaq(ValidacaoCntrl.formataData(null));
            }
        }
    }//GEN-LAST:event_jBTBuscarMaqActionPerformed

    private void jCBCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCategoriaActionPerformed
        if (this.jCBCategoria.getSelectedIndex() != 0) {
            this.jCBCapacidade.setEnabled(true);
        } else {
            this.jCBCor.setEnabled(false);
            this.jCBCapacidade.setEnabled(false);
            this.jCBCapacidade.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jCBCategoriaActionPerformed

    private void jCBCapacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCapacidadeActionPerformed
        if (this.jCBCapacidade.getSelectedIndex() != 0) {
            this.jCBCor.setEnabled(true);
        } else {
            this.jCBCor.setEnabled(false);
            this.jCBCor.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jCBCapacidadeActionPerformed

    private void jBTListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTListarActionPerformed
        this.preencheTabDetalhes(null, null, null, null, null, null);
    }//GEN-LAST:event_jBTListarActionPerformed

    private void jBTBuscarDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTBuscarDetActionPerformed
        Integer capacidade = null;
        String categoria = null;
        String cor = null;
        if (this.jCBCapacidade.getSelectedIndex() != 0) {
            try {
                capacidade = Integer.parseInt(this.jCBCapacidade.getSelectedItem().toString());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Formato de capacidade inválida!\n" + ex.getMessage());
            }
        }
        if (this.jCBCategoria.getSelectedIndex() != 0) {
            categoria = this.jCBCategoria.getSelectedItem().toString();
        }
        if (this.jCBCor.getSelectedIndex() != 0) {
            cor = this.jCBCor.getSelectedItem().toString();
        }
        String data = null;
        if (!this.jFTFData.getText().equals("  -  -    ")) {
            data = this.jFTFData.getText();
        }
        String hora = this.jFTFHora.getText().trim();

        this.preencheTabDetalhes(categoria, capacidade, cor, null, ValidacaoCntrl.formataData(data), hora);
    }//GEN-LAST:event_jBTBuscarDetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTAtual;
    private javax.swing.JButton jBTBuscarDet;
    private javax.swing.JButton jBTBuscarMaq;
    private javax.swing.JButton jBTBuscarTot;
    private javax.swing.JButton jBTListar;
    private javax.swing.JButton jBTMes;
    private javax.swing.JButton jBTSemana;
    private javax.swing.JComboBox<String> jCBCapacidade;
    private javax.swing.JComboBox<String> jCBCategoria;
    private javax.swing.JComboBox<String> jCBCor;
    private javax.swing.JComboBox<String> jCBMaquina;
    private javax.swing.JFormattedTextField jFTFData;
    private javax.swing.JFormattedTextField jFTFData2;
    private javax.swing.JFormattedTextField jFTFData3;
    private javax.swing.JFormattedTextField jFTFHora;
    private javax.swing.JLabel jLBCapacidade;
    private javax.swing.JLabel jLBCategoria;
    private javax.swing.JLabel jLBCor;
    private javax.swing.JLabel jLBData;
    private javax.swing.JLabel jLBData2;
    private javax.swing.JLabel jLBData3;
    private javax.swing.JLabel jLBHora;
    private javax.swing.JLabel jLBMaquina;
    private javax.swing.JLabel jLBPesquisa;
    private javax.swing.JLabel jLBTitulo;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTBProducao;
    // End of variables declaration//GEN-END:variables

    private void preencheTabDetalhes(String categoria, Integer capacidade, String cor, String maquina, String data, String hora) {
        List lista = PRODUCCNTRL.listarDet(categoria, capacidade, cor, maquina, data, hora);
        String[] coluna = {"PRODUTO", "DATA", "HORA", "MAQUINA"};
        Tabela tab = new Tabela(lista, coluna);
        this.jTBProducao.setModel(tab);
    }

    private void preencheTabTotalMaq(String data) {
        List lista = PRODUCCNTRL.listarBuscaMaq(data);
        String[] coluna = {"MÁQUINA", "QUANTIDADE"};
        Tabela tab = new Tabela(lista, coluna);
        this.jTBProducao.setModel(tab);
    }

    private void preencheTabTotalDia(String data) {
        List lista = PRODUCCNTRL.listarDiaTab(data);
        Tabela tab = new Tabela(lista, PRODUCAOTOTAL);
        this.jTBProducao.setModel(tab);
    }

    private void preencheTabTotalSemana() {
        List lista = PRODUCCNTRL.listarSemanaTab();
        Tabela tab = new Tabela(lista, PRODUCAOTOTAL);
        this.jTBProducao.setModel(tab);
    }

    private void preencheTabTotalMes() {
        List lista = PRODUCCNTRL.listarMesTab();
        Tabela tab = new Tabela(lista, PRODUCAOTOTAL);
        this.jTBProducao.setModel(tab);
    }

    private void preencheComboBoxCap() {
        CapacidadeCntrl capCntrl = new CapacidadeCntrl();
        List listaCap = capCntrl.listar();
        this.jCBCapacidade.removeAllItems();
        this.jCBCapacidade.addItem("");
        for (int i = 0; i < listaCap.size(); i++) {
            this.jCBCapacidade.addItem(listaCap.get(i).toString());
        }
    }

    private void preencheComboBoxCat() {
        CategoriaCntrl catCntrl = new CategoriaCntrl();
        List listaCat = catCntrl.listar();
        this.jCBCategoria.removeAllItems();
        this.jCBCategoria.addItem("");
        for (int i = 0; i < listaCat.size(); i++) {
            this.jCBCategoria.addItem(listaCat.get(i).toString());
        }
    }

    private void preencheComboBoxCor() {
        CorCntrl corCntrl = new CorCntrl();
        List listaCor = corCntrl.listar();
        this.jCBCor.removeAllItems();
        this.jCBCor.addItem("");
        for (int i = 0; i < listaCor.size(); i++) {
            this.jCBCor.addItem(listaCor.get(i).toString());
        }
    }

    private void preencheComboBoxMaq() {
        this.jCBMaquina.removeAllItems();
        MaquinaCntrl maqCntrl = new MaquinaCntrl();
        this.jCBMaquina.addItem("");
        List lista = maqCntrl.listar();
        for (int i = 0; i < lista.size(); i++) {
            this.jCBMaquina.addItem(lista.get(i).toString());
        }
    }

}
