/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.controller.ProdutoCntrl;
import br.com.controller.Tabela;
import br.com.exception.GenericSqlException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristiano
 */
public final class ProdutosView extends javax.swing.JPanel {

    /**
     * Creates new form ProdutosView
     */
    public ProdutosView() {
        initComponents();
        preencheTab(null, null);
        this.botao(true, false, false, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPPesquisa = new javax.swing.JPanel();
        jLBPesquisa = new javax.swing.JLabel();
        jLBCategoria = new javax.swing.JLabel();
        jLBCapacidade = new javax.swing.JLabel();
        jBTBuscar = new javax.swing.JButton();
        jTFCategoria = new javax.swing.JTextField();
        jFTFCapacidade = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBProduto = new javax.swing.JTable();
        jBTListar = new javax.swing.JButton();
        jBTExcluir = new javax.swing.JButton();
        jBTAlterar = new javax.swing.JButton();
        jBTAdicionar = new javax.swing.JButton();
        jLBTitulo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPPesquisa.setBackground(new java.awt.Color(255, 255, 255));

        jLBPesquisa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLBPesquisa.setText("PESQUISA:");

        jLBCategoria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBCategoria.setText("CATEGORIA:");

        jLBCapacidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBCapacidade.setText("CAPACIDADE:");

        jBTBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_search_magnifying_glass_find_103857.png"))); // NOI18N
        jBTBuscar.setText("BUSCAR");
        jBTBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTBuscarActionPerformed(evt);
            }
        });

        try {
            jFTFCapacidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCapacidade.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        javax.swing.GroupLayout jPPesquisaLayout = new javax.swing.GroupLayout(jPPesquisa);
        jPPesquisa.setLayout(jPPesquisaLayout);
        jPPesquisaLayout.setHorizontalGroup(
            jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPPesquisaLayout.createSequentialGroup()
                        .addComponent(jLBCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCategoria))
                    .addGroup(jPPesquisaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPPesquisaLayout.createSequentialGroup()
                                .addComponent(jBTBuscar)
                                .addGap(6, 6, 6))
                            .addGroup(jPPesquisaLayout.createSequentialGroup()
                                .addComponent(jLBCapacidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addComponent(jLBPesquisa, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );
        jPPesquisaLayout.setVerticalGroup(
            jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLBPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBCategoria)
                    .addComponent(jTFCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBCapacidade)
                    .addComponent(jFTFCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBTBuscar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTBProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTBProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTBProduto);

        jBTListar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Renew_105218.png"))); // NOI18N
        jBTListar.setText("LISTAR");
        jBTListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTListarActionPerformed(evt);
            }
        });

        jBTExcluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Close_105221.png"))); // NOI18N
        jBTExcluir.setText("EXCLUIR");
        jBTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTExcluirActionPerformed(evt);
            }
        });

        jBTAlterar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Refresh_105225.png"))); // NOI18N
        jBTAlterar.setText("ALTERAR");
        jBTAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAlterarActionPerformed(evt);
            }
        });

        jBTAdicionar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Create_105261.png"))); // NOI18N
        jBTAdicionar.setText("ADICIONAR");
        jBTAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAdicionarActionPerformed(evt);
            }
        });

        jLBTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLBTitulo.setText("PRODUTOS CADASTRADOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBTAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(jBTAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(jBTExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBTListar))
                    .addComponent(jLBTitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLBTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTAdicionar)
                    .addComponent(jBTAlterar)
                    .addComponent(jBTExcluir)
                    .addComponent(jBTListar))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBTAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAdicionarActionPerformed
        AdicionarProdutoDialogView dialog = new AdicionarProdutoDialogView(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jBTAdicionarActionPerformed

    private void jBTAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAlterarActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Alterar um produto pode comprometer todo o sistema.\n Tem certeza que deseja alterar o produto selecionado?");
        if (op == 0) {
            this.setAlterarProduto();
        }

    }//GEN-LAST:event_jBTAlterarActionPerformed

    private void jBTListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTListarActionPerformed
        this.botao(true, false, false, true);
        this.preencheTab(null, null);
    }//GEN-LAST:event_jBTListarActionPerformed

    private void jTBProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBProdutoMouseClicked
        this.botao(true, true, true, true);
    }//GEN-LAST:event_jTBProdutoMouseClicked

    private void jBTBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTBuscarActionPerformed
        String categoria = this.jTFCategoria.getText();
        String cap = this.jFTFCapacidade.getText().trim();
        Integer capacidade = null;
        try {
            if (cap != null && !cap.isEmpty()) {
                capacidade = Integer.parseInt(cap);
            }
            this.preencheTab(categoria, capacidade);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Formato de número inválido!\n" + ex.getMessage());
        }

    }//GEN-LAST:event_jBTBuscarActionPerformed

    private void jBTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTExcluirActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o produto selecionado?");
        if (op == 0) {
            ProdutoCntrl prodCntrl = new ProdutoCntrl();
            try {
                if (prodCntrl.apagar(pegaCodProduto())) {
                    JOptionPane.showMessageDialog(null, "Excluído com sucesso!");
                }
            } catch (GenericSqlException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jBTExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTAdicionar;
    private javax.swing.JButton jBTAlterar;
    private javax.swing.JButton jBTBuscar;
    private javax.swing.JButton jBTExcluir;
    private javax.swing.JButton jBTListar;
    private javax.swing.JFormattedTextField jFTFCapacidade;
    private javax.swing.JLabel jLBCapacidade;
    private javax.swing.JLabel jLBCategoria;
    private javax.swing.JLabel jLBPesquisa;
    private javax.swing.JLabel jLBTitulo;
    private javax.swing.JPanel jPPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBProduto;
    private javax.swing.JTextField jTFCategoria;
    // End of variables declaration//GEN-END:variables

    private void preencheTab(String categoria, Integer capacidade) {
        ProdutoCntrl prodCntrl = new ProdutoCntrl();
        List lista = prodCntrl.listarBuscaTabela(categoria, capacidade);
        String[] coluna = {"CODIGO", "CATEGORIA", "CAPACIDADE", "COR"};
        Tabela tab = new Tabela(lista, coluna);
        this.jTBProduto.setModel(tab);
    }

    private void botao(boolean adicionar, boolean alterar, boolean excluir, boolean listar) {
        this.jBTAdicionar.setEnabled(adicionar);
        this.jBTAlterar.setEnabled(alterar);
        this.jBTExcluir.setEnabled(excluir);
        this.jBTListar.setEnabled(listar);
    }

    private Integer pegaCodProduto() {
        int linha = this.jTBProduto.getSelectedRow();
        Integer prod_id = Integer.parseInt(this.jTBProduto.getValueAt(linha, 0).toString());
        return prod_id;
    }

    private void setAlterarProduto() {
        AlterarProdutoDialogView dialog = new AlterarProdutoDialogView(new javax.swing.JFrame(), true);
        dialog.setCodigoProduto(pegaCodProduto().toString());
        dialog.setVisible(true);
    }
}
