/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.controller.Tabela;
import br.com.controller.ValidacaoCntrl;
import br.com.controller.VendaCntrl;
import br.com.exception.GenericSqlException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristiano
 */
public class VendaView extends javax.swing.JPanel {

    private final VendaCntrl VENDACNTRL = new VendaCntrl();

    /**
     * Creates new form VendaView
     */
    public VendaView() {
        initComponents();
        this.botoes(true, false, false, true);
        this.preencheTab(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPPesquisa = new javax.swing.JPanel();
        jLBData = new javax.swing.JLabel();
        jFTFData = new javax.swing.JFormattedTextField();
        jBTBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBVenda = new javax.swing.JTable();
        jBTListar = new javax.swing.JButton();
        jBTExcluir = new javax.swing.JButton();
        jBTAlterar = new javax.swing.JButton();
        jBTAdicionar = new javax.swing.JButton();
        jLBTitulo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPPesquisa.setBackground(new java.awt.Color(255, 255, 255));

        jLBData.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBData.setText("DATA:");

        try {
            jFTFData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFData.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        jBTBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_search_magnifying_glass_find_103857.png"))); // NOI18N
        jBTBuscar.setText("BUSCAR");
        jBTBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPPesquisaLayout = new javax.swing.GroupLayout(jPPesquisa);
        jPPesquisa.setLayout(jPPesquisaLayout);
        jPPesquisaLayout.setHorizontalGroup(
            jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPesquisaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jBTBuscar))
                    .addGroup(jPPesquisaLayout.createSequentialGroup()
                        .addComponent(jLBData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTFData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPPesquisaLayout.setVerticalGroup(
            jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPesquisaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBData)
                    .addComponent(jFTFData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jBTBuscar)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTBVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTBVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTBVenda);

        jBTListar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Renew_105218.png"))); // NOI18N
        jBTListar.setText("LISTAR");
        jBTListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTListarActionPerformed(evt);
            }
        });

        jBTExcluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Close_105221.png"))); // NOI18N
        jBTExcluir.setText("EXCLUIR");
        jBTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTExcluirActionPerformed(evt);
            }
        });

        jBTAlterar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Refresh_105225.png"))); // NOI18N
        jBTAlterar.setText("ALTERAR");
        jBTAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAlterarActionPerformed(evt);
            }
        });

        jBTAdicionar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBTAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/if_Create_105261.png"))); // NOI18N
        jBTAdicionar.setText("ADICIONAR");
        jBTAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAdicionarActionPerformed(evt);
            }
        });

        jLBTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLBTitulo.setText("VENDA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBTAdicionar)
                .addGap(18, 18, 18)
                .addComponent(jBTAlterar)
                .addGap(18, 18, 18)
                .addComponent(jBTExcluir)
                .addGap(18, 18, 18)
                .addComponent(jBTListar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLBTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLBTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTAdicionar)
                    .addComponent(jBTAlterar)
                    .addComponent(jBTExcluir)
                    .addComponent(jBTListar))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(jPPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jPPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBTAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAdicionarActionPerformed
        ListaProdutosDialogView dialog = new ListaProdutosDialogView(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jBTAdicionarActionPerformed

    private void jBTAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAlterarActionPerformed

        AlterarVenda();
    }//GEN-LAST:event_jBTAlterarActionPerformed

    private void jBTBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTBuscarActionPerformed
        if (!this.jFTFData.getText().equals("  -  -    ")) {
            this.preencheTab(this.jFTFData.getText());
        } else {
            this.preencheTab(null);
        }
    }//GEN-LAST:event_jBTBuscarActionPerformed

    private void jTBVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBVendaMouseClicked
        if (evt.getClickCount() == 1) {
            this.botoes(true, true, true, true);
        }
        if (evt.getClickCount() == 2) {
            AlterarVenda();
        }
    }//GEN-LAST:event_jTBVendaMouseClicked

    private void jBTListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTListarActionPerformed
        this.botoes(true, false, false, true);
        this.preencheTab(null);
    }//GEN-LAST:event_jBTListarActionPerformed

    private void jBTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTExcluirActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover o registro selecionado?");
        if (op == 0) {
            int linha = this.jTBVenda.getSelectedRow();
            try {
                Long mov_id = Long.parseLong(this.jTBVenda.getValueAt(linha, 0).toString());
                if (VENDACNTRL.apagar(mov_id)) {
                    JOptionPane.showMessageDialog(null, "Excluído com sucesso!");
                }
            } catch (GenericSqlException ex) {
                JOptionPane.showMessageDialog(null, "Formato de numero inválido!");
            }
        }
    }//GEN-LAST:event_jBTExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTAdicionar;
    private javax.swing.JButton jBTAlterar;
    private javax.swing.JButton jBTBuscar;
    private javax.swing.JButton jBTExcluir;
    private javax.swing.JButton jBTListar;
    private javax.swing.JFormattedTextField jFTFData;
    private javax.swing.JLabel jLBData;
    private javax.swing.JLabel jLBTitulo;
    private javax.swing.JPanel jPPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBVenda;
    // End of variables declaration//GEN-END:variables

    private void botoes(boolean adicionar, boolean alterar, boolean excluir, boolean lista) {
        this.jBTAdicionar.setEnabled(adicionar);
        this.jBTAlterar.setEnabled(alterar);
        this.jBTExcluir.setEnabled(excluir);
        this.jBTListar.setEnabled(lista);
    }

    private void preencheTab(String data) {
        List lista = VENDACNTRL.buscaListaTabela(ValidacaoCntrl.formataData(data));
        String[] coluna = {"CÓDIGO", "PRODUTO", "QUANTIDADE", "DATA", "HORA"};
        Tabela tab = new Tabela(lista, coluna);
        this.jTBVenda.setModel(tab);
    }

    private void AlterarVenda() {
        int linha = this.jTBVenda.getSelectedRow();
        String codigo = this.jTBVenda.getValueAt(linha, 0).toString();
        String quantidade = this.jTBVenda.getValueAt(linha, 2).toString();
        AlterarVendaDialogView dialog = new AlterarVendaDialogView(new javax.swing.JFrame(), true);
        dialog.setCodigo(codigo);
        dialog.setQuantidade(quantidade);
        dialog.setVisible(true);
    }
}
